[package]
name = "world-study-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
serde_json = "1.0.140"
world-study-data = { path = "../data" }

[[bin]]
name = "generate-country-data"
path = "bin/generate_country_data.rs"
